RegisterNetEvent("spawnPlayerQub3d2", function()
    TriggerEvent("cS.PopupWarning", "~y~Loading~s~", "You are now loading into a Sumo Game.\nPlease wait.", "GlowTM", 10, true)
    TriggerEvent("qub3d:spawncube2")
    SetEntityCoords(PlayerPedId(), 3269.18, 1451.37, 309.38, 180.53, true, true, true, false)
    TriggerEvent("qub3d:spawnplayercar")
    TriggerEvent("qub3d:clouds2") 



end)

RegisterNetEvent("qub3d:clouds2")
AddEventHandler("qub3d:clouds2", function()
    Citizen.Wait(9500)
    StartPlayerSwitch(PlayerPedId(), PlayerPedId(), 255, 1)
    BeginTextCommandBusyspinnerOn("CUSTOMLOADSTRR")
    EndTextCommandBusyspinnerOn(4)
    Citizen.Wait(9000)
    TriggerEvent("qub3d:cam2")
    Citizen.Wait(2000) 
    BusyspinnerOff()
    StopPlayerSwitch()
end)

RegisterNetEvent("qub3d:startsequence22")
AddEventHandler("qub3d:startsequence22", function()

    TriggerEvent("qub3d:explode")
    TriggerEvent("qub3d:openvehiclemenu2")
    TriggerEvent("mt:missiontext", "Select your ~b~Vehicle", 100000)
    Citizen.Wait(30000)
    TriggerEvent("qub3d:startsequence2")
end)

RegisterNetEvent("qub3d:cam2")
AddEventHandler("qub3d:cam2", function()
    print("created camera")
    cam = CreateCam("DEFAULT_SCRIPTED_CAMERA", true)
    SetCamCoord(cam, 3243.22, 1474.78, 307.95)
    SetCamRot(cam, 0.0, 0.0, 230.01, 0.0)
    SetCamActive(cam, true)
    RenderScriptCams(true, true, 1000, true, false)
    DisplayRadar(false)
    DisplayHud(false)
    Citizen.Wait(5000)
    TriggerEvent('cS.banner', "~o~qub3d~s~", "Knock the Enemy Players off the rotating Cube.", 5, true)

    Citizen.Wait(10000)
    DoScreenFadeOut(20)
    DisplayRadar(true)
    DisplayHud(true)
    RenderScriptCams(false, true, 1000, true, false)
    DestroyCam(cam, true)
    print("destroyed camera")
    Citizen.Wait(2000)
    DoScreenFadeIn(1000)
    Citizen.Wait(3000)
    TriggerEvent("qub3d:startsequence22")
end)